FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        // GET: Beneficiario
        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(long Id)
        {
            BoBeneficiario bo = new BoBeneficiario();
            bo.Excluir(Id);
            return Json("Cadastro removido com sucesso");
        }

        [HttpPost]
        public JsonResult Incluir(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();

            if (bo.VerificarExistencia(model.CPF, model.IdCliente))
                return Json(string.Join(Environment.NewLine, "CPF já está cadastrado para este cliente"));

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {

                model.Id = bo.Incluir(new Beneficiario()
                {
                    Nome = model.Nome,
                    IdCliente = model.IdCliente,
                    CPF = model.CPF.Replace(".", "").Replace("-", "")
                });

                return Json("Cadastro efetuado com sucesso");
            }
        }

        [HttpPost]
        public ActionResult Alterar(string list, string idCliente)
        {
            List<Beneficiario> registrosAlterados = new List<Beneficiario>();
            List<Beneficiario> beneficiarios = new BoBeneficiario().Listar(long.Parse(idCliente));


            JArray array = JArray.Parse(list);
            foreach (JObject obj in array.Children<JObject>())
            {
                BeneficiarioModel model = new BeneficiarioModel();
                
                foreach (JProperty singleProp in obj.Properties())
                {
                    string name = singleProp.Name;
                    
                    switch (name)
                    {
                        case "id":
                            model.Id = singleProp.Value.ToString() == "" ? 0 : long.Parse(singleProp.Value.ToString());
                            break;
                        case "cpf":
                            model.CPF = singleProp.Value.ToString();
                            break;
                        case "nome":
                            model.Nome = singleProp.Value.ToString();
                            break;
                    }

                    
                }
                model.IdCliente = long.Parse(idCliente);
                
                BoBeneficiario bo = new BoBeneficiario();

                if (!this.ModelState.IsValid)
                {
                    List<string> erros = (from item in ModelState.Values
                                          from error in item.Errors
                                          select error.ErrorMessage).ToList();

                    Response.StatusCode = 400;
                    return Json(string.Join(Environment.NewLine, erros));
                }
                else
                {
                    if (model.Id != 0)
                    {
                        bo.Alterar(new Beneficiario()
                        {
                            Id = model.Id,
                            Nome = model.Nome,
                            IdCliente = model.IdCliente,
                            CPF = model.CPF.Replace(".", "").Replace("-", "")
                        });
                    }
                    else
                    {
                        model.Id = bo.Incluir(new Beneficiario()
                        {
                            Nome = model.Nome,
                            IdCliente = model.IdCliente,
                            CPF = model.CPF.Replace(".", "").Replace("-", "")
                        });
                    }

                    registrosAlterados.Add( new Beneficiario()
                    {
                        Id = model.Id,
                        Nome = model.Nome,
                        IdCliente = model.IdCliente,
                        CPF = model.CPF.Replace(".", "").Replace("-", "")
                    });
                }
            }

            var Excluidos = beneficiarios.Where(x => !registrosAlterados.Any(z => z.Id == x.Id)).ToList();

            foreach(Beneficiario excluido in Excluidos)
            {
                BoBeneficiario bo = new BoBeneficiario();
                bo.Excluir(excluido.Id);
            }

            return Json("Cadastro alterado com sucesso");
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoBeneficiario bo = new BoBeneficiario();
            Beneficiario beneficiario = bo.Consultar(id);
            Models.BeneficiarioModel model = null;

            if (beneficiario != null)
            {
                model = new BeneficiarioModel()
                {
                    Id = model.Id,
                    Nome = model.Nome,
                    IdCliente = model.IdCliente,
                    CPF = model.CPF.Replace(".", "").Replace("-", "")
                };
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult BeneficiarioList(BeneficiarioModel model)
        {
            try
            {
                List<Beneficiario> beneficiarios = new BoBeneficiario().Listar(model.IdCliente);
                return Json(beneficiarios);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    
    }
}

FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
            
            if(bo.VerificarExistencia(model.CPF))
                return Json(string.Join(Environment.NewLine, "CPF já consta no sistema"));

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                
                model.Id = bo.Incluir(new Cliente()
                {                    
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    CPF = model.CPF.Replace(".", "").Replace("-", "")
                });

           
                return Json(model.Id);
            }
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
       
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                bo.Alterar(new Cliente()
                {
                    Id = model.Id,
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    CPF = model.CPF.Replace(".", "").Replace("-", "")
                });
                
                return Json(model.Id);
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente bo = new BoCliente();
            Cliente cliente = bo.Consultar(id);
            Models.ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    CPF = Convert.ToUInt64(cliente.CPF).ToString(@"000\.000\.000\-00")
                };
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Alterar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';
        var urlAlterarBenef = '@Url.Action("Alterar", "Beneficiario", new { area = "" })';
        var urlIncluirBenef = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
        var urlListarBenef ='@Url.Action("BeneficiarioList", "Beneficiario", new { area = "" })';
        var urlModal = '@Url.Action("Index", "Beneficiario")';
        var urlDeleteBenef = '@Url.Action("Delete", "Beneficiario")';
    </script>
    @Scripts.Render("~/bundles/benef")
    @Scripts.Render("~/bundles/altbenef")
    @Scripts.Render("~/bundles/mascara")
    @Scripts.Render("~/bundles/altClientes")
    <script>
        listBenef(@Html.Raw(Model.Id.ToString()));
    </script>
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

@section modals{
    <div id="modal" class="modal fade" role="dialog" />
}

FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
<form id="formCadastro" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Sobrenome">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="CPF">CPF:</label>
                <input required="required" type="text" class="form-control" id="CPF" name="CPF" placeholder="Ex.: 010.011.111-00" onkeyup="formataCPF(this,event);" maxlength="14">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nacionalidade">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50">
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="CEP">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Estado">Estado:</label>
                <select required="required" id="Estado" class="form-control" name="Estado">
                    <option value="">Selecione</option>
                    <option value="SP">São Paulo</option>
                    <option value="PE">Pernambuco</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Cidade">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="Logradouro">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Email">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Telefone">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <button type="button" class="btn btn-primary btn-outline beneficiarios">Beneficiários</button>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="pull-right">
                <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
            </div>
        </div>
    </div>
</form>

FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
        var urlModal = '@Url.Action("Index", "Beneficiario")';
        var urlIncluirBenef = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
        var urlDeleteBenef = '@Url.Action("Delete", "Beneficiario")';
    </script>
    @Scripts.Render("~/bundles/clientes")
    @Scripts.Render("~/bundles/mascara")
    @Scripts.Render("~/bundles/benef")
    @Scripts.Render("~/bundles/altbenef")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

@section modals{
    <div id="modal" class="modal fade" role="dialog"/>
}

FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
    <script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class = "btn btn-sm btn-primary pull-right" })
<table id="gridClientes" class="table"></table>